Adnug.Arch/Models/Licence.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Adnug.Arch.Models
{
    public class Licence
    {
        public string Key { get; set; }
        public string Name { get; set; }
    }
}

Adnug.Arch/Models/SimpleFormModel.cs
using Adnug.Arch.Validation.Models;
using FluentValidation.Attributes;

namespace Adnug.Arch.Models
{
    [Validator(typeof(SimpleFormModelValidator))]
    public class SimpleFormModel
    {
        public string FirstName { get; set; }
    }
}

Adnug.Arch/Models/ViewModels/LicenceEditModel.cs
using Adnug.Arch.Core.DataTransferObjects;
using Adnug.Arch.Validation.Models.ViewModels;
using FluentValidation.Attributes;

namespace Adnug.Arch.Models.ViewModels
{
    [Validator(typeof(LicenceEditModelValidator))]
    public class LicenceEditModel
    {
        public LicenceDto Licence { get; set; }
    }
}

Adnug.Arch/Models/ViewModels/LicencesViewModel.cs
using System.Collections.Generic;
using Adnug.Arch.Core.DataTransferObjects;

namespace Adnug.Arch.Models.ViewModels
{
    public class LicencesViewModel
    {
        public IEnumerable<LicenceDto> Licences { get; set; }
    }
}

Adnug.Arch/Controllers/HomeController.cs
using System.Net;
using System.Web.Mvc;
using Adnug.Arch.Messaging.Queries;
using Adnug.Arch.Models;
using Adnug.Arch.Mvc.Controllers;
using Adnug.Arch.Mvc.Infrastructure.Alerts;
using Adnug.Arch.Mvc.Infrastructure.Logging;
using MediatR;

namespace Adnug.Arch.Controllers
{
    public class HomeController : SiteController
    {
        public HomeController(ILogger logger, IMediator mediator) 
            : base(logger, mediator)
        {
        }

        public ActionResult Index()
        {
            return View();
            /*.WithSuccess("You arrived")
                .WithInfo("Well done")
                .WithWarning("Be warned");*/
        }

        public ActionResult SimpleForm()
        {

            ViewBag.Message = "";

            var simpleFormModel = new SimpleFormModel { FirstName = "Ian" };

            return View(simpleFormModel);
        }

        [HttpPost]
        public ActionResult SimpleForm(SimpleFormModel simpleFormModel)
        {
            // do nothing

            return JsonSuccess(simpleFormModel);
        }

        public ActionResult SimpleQuery()
        {
            return View();
        }
    }
}

Adnug.Arch/Controllers/LicenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Adnug.Arch.Mvc.Controllers;
using Adnug.Arch.Mvc.Infrastructure.Logging;
using MediatR;

namespace Adnug.Arch.Controllers
{
    public class LicenceController : SiteController
    {
        public LicenceController(ILogger logger, IMediator mediator) 
            : base(logger, mediator)
        {
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

Adnug.Arch/Controllers/api/LicenceController.cs
using System.Web.Http;
using Adnug.Arch.Messaging.Commands;
using Adnug.Arch.Messaging.Queries;
using Adnug.Arch.Models.ViewModels;
using Adnug.Arch.Mvc.Controllers;
using Adnug.Arch.Mvc.Infrastructure.Logging;
using MediatR;

namespace Adnug.Arch.Controllers.api
{
    public class LicenceController : ApiSiteController
    {
        public LicenceController(ILogger logger, IMediator mediator)
            : base(logger, mediator)
        {
            
        }

        [Route("api/licence/{id}")]
        public IHttpActionResult Get(int? id)
        {
            if (!id.HasValue)
                return JsonError("No id was sent to the server");

            GetLicenceQuery getLicenceQuery = new GetLicenceQuery { LicenceId = id.Value };
            LicenceEditModel licenceEditModel = null;

            if (Authorize("View", "AdnugProtectedResource") && Execute(() => licenceEditModel = _mediator.Send(getLicenceQuery)))
            {
                _logger.LogWarning("done");
                return JsonSuccess(licenceEditModel);
            }

            return JsonError(Errors);
        }

        [Route("api/licence")]
        public IHttpActionResult Post(LicenceEditModel licenceEditModel)
        {
            var updateLicenceCommand = new UpdateLicenceCommand { LicenceEditModel = licenceEditModel };
            int licenceId = -1;

            if (Execute(() => _mediator.Send(updateLicenceCommand)))
            {
                return JsonSuccess(licenceEditModel);
            }

            return JsonError(Errors);
        }
    }
}

Adnug.Arch/Controllers/api/LicensingController.cs
using System.Web.Http;
using Adnug.Arch.Messaging.Queries;
using Adnug.Arch.Models.ViewModels;
using Adnug.Arch.Mvc.Controllers;
using Adnug.Arch.Mvc.Infrastructure.Logging;
using MediatR;

namespace Adnug.Arch.Controllers.api
{
    public class LicensingController : ApiSiteController
    {

        public LicensingController(ILogger logger, IMediator mediator)
            : base(logger, mediator)
        {
        }

        [Route("api/licensing")]
        public IHttpActionResult Get()
        {
            LicencesViewModel licencesViewModel = null;

            if (Execute(() => licencesViewModel = _mediator.Send(new GetLicencesQuery())))
            {
                return JsonSuccess(licencesViewModel);
            }

            return JsonError(Errors);
        }
    }
}

Adnug.Arch/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2>Landing Page Architecture Demo</h2>

<div ng-controller="HomeController" class="col-xs-12">
    <div class="row">
        <div ng-bind="msg"></div>
    </div>
</div>

Adnug.Arch/Views/Home/SimpleForm.cshtml
@model Adnug.Arch.Models.SimpleFormModel

@{
    ViewBag.Title = "SimpleForm";
}

<h2>Simple Form - Model State Demo</h2>

<div ng-controller="SimpleFormController">
    <div class="row" ng-init="editModel = {};editModel.simpleFormModel = {};editModel.simpleFormModel.firstName = '@Model.FirstName'">
        <form name="simpleFormDemo" ng-submit="submit($event)" novalidate autocomplete="off">

            <div ad-form-input>
                <label for="name">Name:</label>
                <input type="text" id="name" name="simpleFormModelFirstName" placeholder="Enter given name" ng-model="editModel.simpleFormModel.firstName" 
                       required ng-minlength="2" ng-maxlength="3">
            </div>

            <button type="submit" class="btn btn-default">Submit</button>

        </form>
    </div>
</div>

Adnug.Arch/Views/Home/SimpleQuery.cshtml
@{
    ViewBag.Title = "SimpleQuery";
}

<h2>Simple Demo of Query Handler</h2>

<div ng-controller="SimpleQueryDemoController">
    <div class="row">

        <table class="table">
            <thead>
                <tr>
                    <th>Licence Id</th>
                    <th>Licence Key</th>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="licence in viewModel.licences">
                    <td>{{licence.id}}</td>
                    <td>{{licence.licenceKey}}</td>
                </tr>
            </tbody>
        </table>

    </div>
</div>

Adnug.Arch/Views/Licence/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<div class="row" ng-controller="LicenceController">

    <div class="top40">
        <form name="parentForm" ng-submit="submit($event)" novalidate autocomplete="off">

            @Html.AntiForgeryToken()

            <ng-form name="getLicenceForm" novalidate ng-if="!licenceRetrieved">
                
                <div ad-form-input>
                    <label for="licenceId">Licence Id</label>
                    <input type="text" required id="licenceId" placeholder="Enter id for licence" ng-model="$parent.licenceId">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </ng-form>

            <ng-form name="editLicenceForm" novalidate ng-if="licenceRetrieved">
                <div ad-form-input>
                    <label for="licenceId">Licence Id</label>
                    <input type="text" required id="licenceId" name="licenceLicenceId" readonly="readonly" placeholder="Enter id for licence" ng-model="editModel.licence.id">
                </div>
                <div ad-form-input>
                    <label for="licenceKey">Licence Key</label>
                    <input type="text" required id="licenceKey" name="licenceEditModelLicenceLicenceKey" placeholder="Enter key for licence" ng-model="editModel.licence.licenceKey">
                </div>
                <div ad-form-input>
                    <label for="softwareNameAndDescription">Name and Description</label>
                    <input type="text" ad-has-colon required id="softwareNameAndDescription" name="licenceEditModelLicenceSoftwareNameAndDescription" placeholder="Enter name and description for software" ng-model="editModel.licence.software.nameAndDescription">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>

            </ng-form>

        </form>
    </div></div>

Adnug.Arch/Views/Shared/_Alerts.cshtml
@using Adnug.Arch.Mvc.Infrastructure.Alerts
@if (TempData.GetAlerts().Any())
{
    <script>
		$(function() {
			@foreach (var alert in TempData.GetAlerts())
			{
				<text>
				window.alerts.showAlert({
					message: '@alert.Message.Replace("'", "\\'")',
					alertClass: '@alert.AlertClass'
				});
				</text>
			}
		});
    </script>
}

Adnug.Arch/Views/Shared/_Constants.cshtml
@using Adnug.Arch.Mvc.Infrastructure
@{
    <script>
        var serverConstants = {
            delimiter: '@UiConstants.Delimiter'
        };
        var sc = serverConstants;
    </script>
}

Adnug.Arch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="adnugApp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <base href="/" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <i class="navbar-brand fa fa-building-o"></i> @Html.ActionLink("ADNUG Arch Demo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Simple Form", "SimpleForm", "Home")</li>
                    <li>@Html.ActionLink("Simple Query", "SimpleQuery", "Home")</li>
                    <li>@Html.ActionLink("Edit Licence", "Index", "Licence")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        <div class="alert-container"></div>
        <div class="alert-sticky"></div>
        @RenderBody()
    </div>

    <footer class="container" >
        <hr />
        <p>ADNUG Demo - Footer stuff and legal bla bla to keep us out of trouble. </p>
    </footer>


    @Html.Partial("_Constants")
    @Scripts.Render("~/bundles/libraries")
    @Scripts.Render("~/bundles/app")
    @Html.Partial("_Alerts")
    @RenderSection("scripts", required: false)
</body>
</html>